### ISSUE TITLE
wha scitto is ded?

### ISSUE THREAD

**Issue by 1to5pc** [Senhas-t/CaringCyberDemos#2]
Sheesh

**Comment by sandrew-parker** [comment]
Indeed, Now mainly is it; Sandrew Parker.

**Comment by 1to5pc** [comment]
huh ok

**Comment by Senhas-t** [comment]
Pls this issue completely not relevant to this rep.

**Comment by sandrew-parker** [comment]
Yes, but remove Scitto from the script. And also, correct my name.
